### ISSUE TITLE
Is here a plan to support the carrier board eeprom read/write ?

### ISSUE THREAD

**Issue by bigbearishappy** [madisongh/tegra-eeprom-tool#10]
According to the latest JetPack doc in [here](https://docs.nvidia.com/jetson/archives/r36.3/DeveloperGuide/HR/JetsonEepromLayout.html).

A Jetson system has two EEPROMs, one on the module and one on the carrier board. But in this repo. We can only read/write the eeprom on the jetson module.

So do you have a plan to support read/write the eeprom on the carrier board?

Looking forward to your reply~

**Comment by madisongh** [comment]
There is the `-d` option you can use to specify the device. You have to know the I2C address of the CVB EEPROM, but that should work.

**Comment by bigbearishappy** [comment]
Thank you. It works fine now.
Here is my test cmd:
```
./tegra-eeprom-tool -d 0-0x57 show
```
