### ISSUE TITLE
[Jetson Nano] TNSPEC: FAB <-> part number version?

### ISSUE THREAD

**Issue by Aufschlauer** [madisongh/tegra-eeprom-tool#7]
Hi,

we've an issue with a single Jetson Nano SoM: The mender update failed.

Usually, for our SoM's, the TNSPEC (generated by `tegra_boardspec()`) looks like this:
`3448-400-0002-F.0-...`, but with the problematic SoM the TNSPEC looks like this: `3448-401-0002-F.0-...`. According to [Part number is 699-8bbbb-ssss-fff RRR](https://github.com/OE4T/tegra-eeprom-tool/blob/68ae8352e13b3a4bf47301c5fc2c6c496e981c84/boardspec.c#L65) the change was been made within the FAB entry: From `400` to `401`.

But, according to [Jetson Module EEPROM Layout](https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3251/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/jetson_eeprom_layout.html), the entry identified as FAB is in the Jetson EEPROM layout the `version` entry. Here is the code snippet from `tegra_boardspec()`:
```C
return snprintf(buf, bufsiz,
			"%-4.4s-%-3.3s-%-4.4s-%s-1-%u",
			&eeprom.partnumber[5],
			&eeprom.partnumber[15],
			&eeprom.partnumber[10],
			boardrev,
			(soctype == TEGRA_SOCTYPE_194 ? 2 : 0));
```
The FAB entry of the TNSPEC is made out of the `version` entry of the partnumber.

So, the question is whether FAB and the `version` entry of the partnumber is same or is this a mistake or is this by intention?

I couldn't find more information regarding the meaning of FAB.

Can anyone give me a hint?

Thanks.

**Comment by madisongh** [comment]
Yes, the FAB is the board version.  Make sure your BUP payload includes entries for `fab=401` to cover that version of the Nano board.

**Comment by Aufschlauer** [comment]
Ok, thanks.

May I ask a BUP related question here?

It is the first time we face such issue. So, just to ensure I got you right: The entry for the BUP payload has to be appended to Yocto's `TEGRA_BUPGEN_SPECS` environment variable, right? _(We can't test a new mender image, because we don't have the problematic SoM present)_

**Comment by madisongh** [comment]
Historically, that has been the case, yes.  And unfortunately, we didn't know in advance what those entries should be.

Stock JetPack/L4T has the concept of "compatibility" specs that map BUP entries generated against older hardware revisions to newer ones.  It took some time to figure out how to adapt that compatibility checking to Yocto builds, but we do have that feature now in the `kirkstone` and later branches (including `kirkstone-l4t-r32.7.x` for the TX1/TX2/Nano hardware).  If/when you can update your builds to a point where that compatibility check is supported, this should be less of an issue.

**Comment by Aufschlauer** [comment]
>  If/when you can update your builds to a point where that compatibility check is supported, this should be less of an issue.

Well, we've to stick to hardknott for now.
But we were able to fix the "new" FAB entry.
Thanks for your help.
